### ISSUE TITLE
error logs

### ISSUE THREAD

**Issue by fakeoff0** [Lord-FEAR/Discord_Admin_Log#1]
Возможно ли будет исправить?

L 05/12/2019 - 21:51:09: [SM] Blaming: Discord/Core.smx
L 05/12/2019 - 21:51:09: [SM] Call stack trace:
L 05/12/2019 - 21:51:09: [SM]   [0] ThrowNativeError
L 05/12/2019 - 21:51:09: [SM]   [1] Line 107, discord/API.sp::API_SetUsername
L 05/12/2019 - 21:51:09: [SM]   [3] Discord_SetUsername
L 05/12/2019 - 21:51:09: [SM]   [4] Line 163, .\discord_log_admin.sp::discord_send_message
L 05/12/2019 - 21:51:09: [SM]   [5] Line 87, .\discord_log_admin.sp::OnLogAction
L 05/12/2019 - 21:51:09: [SM]   [7] LogAction
L 05/12/2019 - 21:51:09: [SM]   [8] Line 529, super_adminka/SayTranslite.sp::SayTranslite
L 05/12/2019 - 21:51:09: [SM]   [9] Line 74, super_adminka/Command_Invisible.sp::Invisible
L 05/12/2019 - 21:51:09: [SM]   [10] Line 28, super_adminka/Command_Invisible.sp::MenuHandler_MenuInvisible
L 05/12/2019 - 21:51:14: [SM] Exception reported: Username must be between 2 and 32 in length.
L 05/12/2019 - 21:51:14: [SM] Blaming: Discord/Core.smx
L 05/12/2019 - 21:51:14: [SM] Call stack trace:
L 05/12/2019 - 21:51:14: [SM]   [0] ThrowNativeError
L 05/12/2019 - 21:51:14: [SM]   [1] Line 107, discord/API.sp::API_SetUsername
L 05/12/2019 - 21:51:14: [SM]   [3] Discord_SetUsername
L 05/12/2019 - 21:51:14: [SM]   [4] Line 163, .\discord_log_admin.sp::discord_send_message
L 05/12/2019 - 21:51:14: [SM]   [5] Line 87, .\discord_log_admin.sp::OnLogAction
L 05/12/2019 - 21:51:14: [SM]   [7] LogAction
L 05/12/2019 - 21:51:14: [SM]   [8] Line 529, super_adminka/SayTranslite.sp::SayTranslite
L 05/12/2019 - 21:51:14: [SM]   [9] Line 74, super_adminka/Command_Invisible.sp::Invisible
L 05/12/2019 - 21:51:14: [SM]   [10] Line 27, super_adminka/Command_Invisible.sp::MenuHandler_MenuInvisible

L 05/12/2019 - 22:58:12: [SM] Blaming: Discord/Core.smx
L 05/12/2019 - 22:58:12: [SM] Call stack trace:
L 05/12/2019 - 22:58:12: [SM]   [0] ThrowNativeError
L 05/12/2019 - 22:58:12: [SM]   [1] Line 107, discord/API.sp::API_SetUsername
L 05/12/2019 - 22:58:12: [SM]   [3] Discord_SetUsername
L 05/12/2019 - 22:58:12: [SM]   [4] Line 163, .\discord_log_admin.sp::discord_send_message
L 05/12/2019 - 22:58:12: [SM]   [5] Line 87, .\discord_log_admin.sp::OnLogAction
L 05/12/2019 - 22:58:12: [SM]   [7] LogAction
L 05/12/2019 - 22:58:12: [SM]   [8] Line 97, super_adminka/Command_Teleport.sp::Teleport_ClientToClient
L 05/12/2019 - 22:58:12: [SM]   [9] Line 751, super_adminka/Menu.sp::MenuHandler_MenuTarget
L 05/12/2019 - 23:02:14: [SM] Exception reported: Username must be between 2 and 32 in length.
L 05/12/2019 - 23:02:14: [SM] Blaming: Discord/Core.smx
L 05/12/2019 - 23:02:14: [SM] Call stack trace:
L 05/12/2019 - 23:02:14: [SM]   [0] ThrowNativeError
L 05/12/2019 - 23:02:14: [SM]   [1] Line 107, discord/API.sp::API_SetUsername
L 05/12/2019 - 23:02:14: [SM]   [3] Discord_SetUsername
L 05/12/2019 - 23:02:14: [SM]   [4] Line 163, .\discord_log_admin.sp::discord_send_message
L 05/12/2019 - 23:02:14: [SM]   [5] Line 145, .\discord_log_admin.sp::OnTodoReceived

**Comment by Lord-FEAR** [comment]
А как это могло произойти? Было бы не плохо увидеть ссылку на профиль админа на которого срабатывает данная ошибка.
Что в ядре дискорда, что в самом стиме на имена стоят ограничения от 2 до 32 символов, а здесь как раз ошибка что их больше или меньше.
В моем плагине ограничение установлено на 50 символов, а ошибка эта идёт с ядра дискорда
